services:
  - type: web
    name: ecommerce-platform
    env: node
    buildCommand: |
      npm install
      cd client
      npm install
      npm run build
      cd ..
      npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: ecommerce-db
    databaseName: ecommerce_db
    user: ecommerce_user
    plan: free
